[package]
name = "machine-score"
version = "0.1.0"
edition = "2021"
rust-version = "1.91"

[dependencies]
eframe = "0.33"
sysinfo = "0.38"
wgpu = "30"
pollster = "1"
image = { version = "0.25", default-features = false, features = ["png"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = 2
strip = true
